title: ZenOS Wiki
description: Bare-metal OS with userspace and X11
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

url: https://hellokhe.github.io

nav_enabled: true
search_enabled: true

# Sidebar order
nav_sort: case_sensitive

callouts:
  warning:
    title: Warning
    color: yellow

just_the_docs:
  collections:
    features:
      name: Features
      nav_fold: true
