title: ZenOS Wiki
description: Bare-metal OS with userspace and X11
remote_theme: just-the-docs/just-the-docs

url: https://hellokhe.github.io

nav_enabled: true
search_enabled: true

nav_sort: case_sensitive

extra_css:
  - /assets/css/custom.css

callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: yellow

collections:
  features:
    output: true

just_the_docs:
  collections:
    features:
      name: Features
      nav_fold: true
